"""Данные «Летописи Небес» (docs/LORE.md): книги, узлы ленты «Нить», листы, Глоссарий.

Всё, что видит игрок, лежит здесь одним файлом; gen_lore.py превращает это в переводы, JSON для игры и иллюстрации.
Правила (LORE §0–§1, §8): текст — приправа, а не блюдо (лист = кадр + 1–3 строки); эпиграф — только Синодальный перевод (ru) и KJV (en),
без текста, если точность цитаты не гарантирована (тогда только ссылка); «Писание» (s), «Апокриф Небес» (a) и «Предание» (t) помечаются явно.
Бог и Христос не изображаются.

Лист: id, book, node, art (мотив картинки в gen_lore.ART), src (как открывается), how (ru, en — подсказка о том, где искать),
title, ref (ru, en) или None, quote (ru Синодальный, en KJV) или None, s / a / t (ru, en) или None, gloss — слова Глоссария,
которые лист открывает вместе с собой.

src: prologue — пролог «Сон о Начале»; glimpse — Отблеск (S3); names — Книга Имён; vision — видение в Саду; scroll — свиток;
tablet — скрижаль; conv — беседа; deed — подвиг (босс, постройка, испытание); place — приход в место.
"""

BOOKS = {
    1: ('Книга Начала', 'The Book of the Beginning'),
    2: ('Книга Стражей', 'The Book of the Watchers'),
    3: ('Книга Вод', 'The Book of the Waters'),
    4: ('Книга Башни', 'The Book of the Tower'),
    5: ('Книга Странников', 'The Book of the Wanderers'),
    6: ('Книга Чинов', 'The Book of the Choirs'),
    7: ('Книга Откровения', 'The Book of Revelation'),
}

# Узлы ленты «Нить»: (id, ru, en, акт, которому соответствует; 0 — нет). Порядок — вдоль линии времени.
NODES = [
    ('light', 'Свет', 'Light', 0),
    ('morning', 'Денница', 'Morning Star', 0),
    ('eden', 'Эдем', 'Eden', 0),
    ('exile', 'Изгнание', 'Exile', 1),
    ('brothers', 'Каин и Авель', 'Cain and Abel', 0),
    ('watchers', 'Стражи', 'Watchers', 2),
    ('flood', 'Потоп', 'The Flood', 3),
    ('babel', 'Вавилон', 'Babel', 4),
    ('prophets', 'Пророки', 'Prophets', 0),
    ('revelation', 'Откровение', 'Revelation', 5),
]

# Листы, у которых способ открыться появится в своей задаче (lint_assets.check_lore печатает их отдельно): id → где.
PENDING = {'morning_star': 'S3.7 «Осколки падения»'}

SOURCES = ('prologue', 'glimpse', 'names', 'vision', 'scroll', 'tablet', 'conv', 'deed', 'place')

SHEETS = [
    # ---------------------------------------------------------------- Книга Начала
    dict(id='light', book=1, node='light', art='light', src='prologue',
         how=('Сон о Начале — первое, что видит странник', 'The Dream of the Beginning, the first thing a wanderer sees'),
         title=('Первый свет', 'The First Light'),
         ref=('Быт. 1:3', 'Gen. 1:3'),
         quote=('И сказал Бог: да будет свет. И стал свет.', 'And God said, Let there be light: and there was light.'),
         s=('Из тьмы над бездной Бог призвал свет и отделил его от тьмы.',
            'God called light out of the darkness over the deep and set it apart from the dark.'),
         a=('Свет помнит всё, что было при нём. Потому странник, несущий в себе Благодать, способен увидеть былое.',
            'Light remembers all that happened by it. So a wanderer who carries Grace can behold what was.'),
         gloss=['grace']),
    dict(id='eden', book=1, node='eden', art='garden', src='prologue',
         how=('Сон о Начале: Сад, где всё было названо', 'The Dream of the Beginning: the Garden where all was named'),
         title=('Сад на востоке', 'A Garden Eastward'),
         ref=('Быт. 2:8', 'Gen. 2:8'),
         quote=('И насадил Господь Бог рай в Едеме на востоке, и поместил там человека, которого создал.',
                'And the LORD God planted a garden eastward in Eden; and there he put the man whom he had formed.'),
         s=('Первый человек был поселён в саду, где росли два дерева: жизни и познания.',
            'The first man was set in a garden where two trees grew: of life and of knowledge.'),
         a=('После изгнания Сад не погиб, а был поднят над облаками. Острова Рая — его осколки.',
            'After the exile the Garden did not perish; it was raised above the clouds. The islands of Heaven are its shards.'),
         gloss=['eden']),
    dict(id='names', book=1, node='eden', art='names', src='names',
         how=('Книга Имён: запиши в Бестиарий восемь существ (победи или встреть их)', 'The Book of Names: record eight creatures in the Bestiary (defeat or meet them)'),
         title=('Имена', 'Names'),
         ref=('Быт. 2:19', 'Gen. 2:19'),
         quote=('…и чтобы, как наречёт человек всякую душу живую, так и было имя ей.',
                '…and whatsoever Adam called every living creature, that was the name thereof.'),
         s=('Человек дал имя каждому живому существу, и названное стало ему близким.',
            'The man gave a name to every living creature, and the named became near to him.'),
         a=('Книга Имён в Кодексе хранит эту работу: существо, которое ты назвал, уже не чужое.',
            'The Book of Names in the Codex keeps that labour: a creature you have named is no longer a stranger.'),
         gloss=[]),
    dict(id='tree_life', book=1, node='eden', art='tree_life', src='vision',
         how=('Видение у Древа Жизни в Саду Начала', 'A vision at the Tree of Life in the Garden of the Beginning'),
         title=('Древо Жизни', 'The Tree of Life'),
         ref=('Быт. 2:9', 'Gen. 2:9'),
         quote=('…и дерево жизни посреди рая, и дерево познания добра и зла.',
                '…the tree of life also in the midst of the garden, and the tree of knowledge of good and evil.'),
         s=('Посреди сада стояли два дерева. Одно хранило жизнь, от другого есть не велено.',
            'Two trees stood in the midst of the garden. One kept life; of the other none might eat.'),
         a=('Цитадель Рая стоит там, где росло Древо Жизни. Его плод возвращает силы.',
            'The Citadel of Heaven stands where the Tree of Life grew. Its fruit restores strength.'),
         gloss=[]),
    dict(id='fruit', book=1, node='eden', art='fruit', src='glimpse',
         how=('Отблеск: Древо Познания в Саду Начала', 'A Glimpse: the Tree of Knowledge in the Garden of the Beginning'),
         title=('Плод', 'The Fruit'),
         ref=('Быт. 3:6', 'Gen. 3:6'),
         quote=('…и взяла плодов его и ела; и дала также мужу своему, и он ел.',
                '…she took of the fruit thereof, and did eat, and gave also unto her husband with her; and he did eat.'),
         s=('Они вкусили плод, и у обоих открылись глаза: пришли знание, а с ним и стыд.',
            'They tasted the fruit and the eyes of both were opened: knowledge came, and shame with it.'),
         a=('Древо Познания в Саду заросло терновником. Кто коснётся его коры, увидит, как это было.',
            'The Tree of Knowledge in the Garden is overgrown with thorns. Whoever touches its bark will see how it was.'),
         gloss=[]),
    dict(id='exile', book=1, node='exile', art='exile', src='glimpse',
         how=('Отблеск: Восточные врата Эдема', 'A Glimpse: the East Gate of Eden'),
         title=('Изгнание', 'The Exile'),
         ref=('Быт. 3:23', 'Gen. 3:23'),
         quote=None,
         s=('Человека выслали из Сада возделывать землю, из которой он был взят.',
            'The man was sent out of the Garden to till the ground from which he was taken.'),
         a=('Верхний мир — земля изгнания. Угасание — это свет, уходящий вслед за Эдемом.',
            'The Upper World is the land of exile. The Fading is the light going out after Eden.'),
         gloss=['fading']),
    dict(id='flaming_sword', book=1, node='exile', art='sword', src='deed',
         how=('Пройди мимо пламенного меча у Восточных врат', 'Pass the flaming sword at the East Gate'),
         title=('Пламенный меч', 'The Flaming Sword'),
         ref=('Быт. 3:24', 'Gen. 3:24'),
         quote=('…и поставил на востоке у сада Едемского Херувима и пламенный меч, обращающийся, чтобы охранять путь к дереву жизни.',
                '…he placed at the east of the garden of Eden Cherubims, and a flaming sword which turned every way, to keep the way of the tree of life.'),
         s=('Путь к Древу Жизни закрыли страж и вращающийся пламенный меч.',
            'The way to the Tree of Life was shut by a guardian and a turning flaming sword.'),
         a=('Когда Сад подняли в облака, Херувим остался у врат. Меч не трогает тех, в ком есть Благодать, но помнит каждого, кто ел от Древа Познания.',
            'When the Garden was lifted into the clouds the Cherub remained at the gate. The sword spares those who bear Grace, but remembers all who ate of the Tree of Knowledge.'),
         gloss=['cherub']),
    dict(id='cain_abel', book=1, node='brothers', art='altars', src='glimpse',
         how=('Отблеск: два алтаря в Бездне', 'A Glimpse: the two altars in the Abyss'),
         title=('Два алтаря', 'Two Altars'),
         ref=('Быт. 4:4–5', 'Gen. 4:4–5'),
         quote=('И призрел Господь на Авеля и на дар его, а на Каина и на дар его не призрел.',
                'And the LORD had respect unto Abel and to his offering: But unto Cain and to his offering he had not respect.'),
         s=('Дар Авеля был принят, дар Каина — нет; обиженный брат поднял руку на брата.',
            'Abel\'s gift was accepted and Cain\'s was not; the aggrieved brother lifted his hand against his brother.'),
         a=('В Бездне стоят два алтаря, и дым над одним стелется по земле. От них ведут следы того, кто ушёл навсегда.',
            'Two altars stand in the Abyss, and the smoke over one creeps along the ground. The tracks of one who left for ever lead away from them.'),
         gloss=[]),
    dict(id='mark', book=1, node='brothers', art='mark', src='conv',
         how=('Беседа с Каином-Скитальцем', 'A talk with Cain the Wanderer'),
         title=('Знамение Каина', 'The Mark of Cain'),
         ref=('Быт. 4:15', 'Gen. 4:15'),
         quote=('И сделал Господь Бог Каину знамение, чтобы никто, встретившись с ним, не убил его.',
                'And the LORD set a mark upon Cain, lest any finding him should kill him.'),
         s=('Каина не убили: на нём было знамение, чтобы никто не тронул изгнанника.',
            'Cain was not slain: a mark was set on him that none should touch the outcast.'),
         a=('Каина-Скитальца не трогают твари. Встретишь его трижды: в Бездне, в городе, который он основал, и среди звёзд.',
            'Creatures do not touch Cain the Wanderer. You will meet him thrice: in the Abyss, in the city he founded, and among the stars.'),
         gloss=[]),
    # ---------------------------------------------------------------- Книга Стражей
    dict(id='watchers', book=2, node='watchers', art='watchers', src='conv',
         how=('Беседа с прикованным Стражем в Темнице', 'A talk with a chained Watcher in the Prison'),
         title=('Наблюдатели', 'The Watchers'),
         ref=('Быт. 6:2', 'Gen. 6:2'),
         quote=('…тогда сыны Божии увидели дочерей человеческих, что они красивы, и брали их себе в жёны, какую кто избрал.',
                '…the sons of God saw the daughters of men that they were fair; and they took them wives of all which they chose.'),
         t=('Предание (Книга Еноха): двести ангелов-Стражей сошли на гору и связали себя клятвой.',
            'Tradition (Book of Enoch): two hundred angel Watchers came down upon a mountain and bound themselves by an oath.'),
         a=('Падшие стражи Рая и Бездны — те самые Григори, что не вернулись на небо.',
            'The Fallen Guardians of Heaven and the Abyss are those very Watchers who never returned to the sky.'),
         gloss=['watcher']),
    dict(id='azazel', book=2, node='watchers', art='forge', src='scroll',
         how=('Свиток из Небесной кузни', 'A scroll from the Heavenly Forge'),
         title=('Кузнец Азазель', 'Azazel the Smith'),
         ref=('Книга Еноха 8:1', 'Book of Enoch 8:1'),
         quote=None,
         t=('Предание: Азазель научил людей ковать мечи и украшать себя; так в мир пришли война и тщеславие.',
            'Tradition: Azazel taught men to forge swords and adorn themselves; so war and vanity entered the world.'),
         a=('Небесная кузня когда-то была его кузней. Уриил очистил её светом, но меч остался мечом.',
            'The Heavenly Forge was once his. Uriel cleansed it with light, but a sword stayed a sword.'),
         gloss=[]),
    dict(id='nephilim', book=2, node='watchers', art='giant', src='deed',
         how=('Победи Нефилима в Темнице Стражей', 'Defeat the Nephilim in the Prison of the Watchers'),
         title=('Исполины', 'The Giants'),
         ref=('Быт. 6:4', 'Gen. 6:4'),
         quote=('В то время были на земле исполины…', 'There were giants in the earth in those days…'),
         s=('От союза Стражей и людей родились великаны.', 'From the union of Watchers and men giants were born.'),
         a=('В Темнице Стражей ещё бродит один из них. Против великана хороша праща: малый камень бьёт большого.',
            'One of them still prowls the Prison of the Watchers. A sling serves against a giant: a small stone fells a great one.'),
         gloss=['nephilim']),
    dict(id='enoch', book=2, node='watchers', art='enoch', src='conv',
         how=('Беседа с Метатроном-Писцом в Цитадели', 'A talk with Metatron the Scribe in the Citadel'),
         title=('Енох', 'Enoch'),
         ref=('Быт. 5:24', 'Gen. 5:24'),
         quote=('И ходил Енох пред Богом; и не стало его, потому что Бог взял его.',
                'And Enoch walked with God: and he was not; for God took him.'),
         s=('Енох ходил пред Богом, и Бог взял его живым.', 'Enoch walked with God, and God took him alive.'),
         t=('Предание видит в нём Метатрона, Писца небесных книг.', 'Tradition sees in him Metatron, Scribe of the heavenly books.'),
         a=('Метатрон-Писец ведёт Летопись, которую ты листаешь.', 'Metatron the Scribe keeps the Chronicle you are leafing through.'),
         gloss=['metatron']),
    dict(id='chains', book=2, node='watchers', art='chains', src='glimpse',
         how=('Отблеск: цепь у Темницы Стражей', 'A Glimpse: the chain at the Prison of the Watchers'),
         title=('Скованные', 'In Chains'),
         ref=('Иуд. 1:6', 'Jude 1:6'),
         quote=None,
         s=('Ангелов, оставивших свой чин, сохранили в вечных узах под мраком до великого суда.',
            'The angels who kept not their first estate are reserved in everlasting chains under darkness unto the judgment of the great day.'),
         a=('Воинство Небес повело Стражей в цепях вниз, к Темнице. Потому Падшие стражи враждебны.',
            'The host of Heaven led the Watchers down in chains to the Prison. That is why the Fallen Guardians are hostile.'),
         gloss=[]),
    dict(id='abaddon', book=2, node='watchers', art='abyss', src='deed',
         how=('Победи Пожирателя Света в его Логове', 'Defeat the Light Devourer in its Lair'),
         title=('Аваддон', 'Abaddon'),
         ref=('Откр. 9:11', 'Rev. 9:11'),
         quote=('…имя ему по-еврейски Аваддон, а по-гречески Аполлион.',
                '…whose name in the Hebrew tongue is Abaddon, but in the Greek tongue hath his name Apollyon.'),
         s=('Над саранчой из бездны стоит ангел бездны; его имя значит «Губитель».',
            'Over the locusts from the pit stands the angel of the bottomless pit; his name means "Destroyer".'),
         a=('Пожиратель Света — тень Аваддона: он глотает свет, потому что не имеет своего.',
            'The Light Devourer is a shadow of Abaddon: it swallows light because it has none of its own.'),
         gloss=['abyss', 'abaddon']),
    dict(id='morning_star', book=2, node='morning', art='star_fall', src='deed',
         how=('Осколки падения: память побеждённых', 'Shards of the Fall: the memory of the defeated'),
         title=('Денница', 'The Morning Star'),
         ref=('Ис. 14:12', 'Isa. 14:12'),
         quote=('Как упал ты с неба, денница, сын зари! разбился о землю, попиравший народы.',
                'How art thou fallen from heaven, O Lucifer, son of the morning! how art thou cut down to the ground, which didst weaken the nations!'),
         s=('Пророк называет «Денницей», «светоносным», того, кто упал с неба.',
            'The prophet calls him the Morning Star, the light-bringer, who fell from heaven.'),
         a=('Безликий потерял при падении и имя, и облик. Свет он ест, потому что больше не может светить сам.',
            'In his fall the Faceless lost both name and face. He devours light because he can no longer shine.'),
         gloss=[]),
    # ---------------------------------------------------------------- Книга Вод
    dict(id='firmament_waters', book=3, node='flood', art='waters', src='place',
         how=('Войди в Ледяные Чертоги', 'Enter the Frozen Halls'),
         title=('Воды над твердью', 'Waters Above the Firmament'),
         ref=('Быт. 1:7', 'Gen. 1:7'),
         quote=('И создал Бог твердь, и отделил воду, которая под твердью, от воды, которая над твердью. И стало так.',
                'And God made the firmament, and divided the waters which were under the firmament from the waters which were above the firmament: and it was so.'),
         s=('Бог развёл воды: одни остались под небесным сводом, другие поднялись над ним.',
            'God parted the waters: some stayed beneath the vault of heaven, others rose above it.'),
         a=('Когда Потоп отступил, часть вод ушла за твердь и замёрзла. Так возникли Ледяные Чертоги.',
            'When the Flood receded some of the waters went beyond the firmament and froze. So the Frozen Halls came to be.'),
         gloss=['firmament']),
    dict(id='flood', book=3, node='flood', art='flood', src='glimpse',
         how=('Отблеск: обломок Ковчега в Ледяных Чертогах', 'A Glimpse: the wreck of the Ark in the Frozen Halls'),
         title=('Потоп', 'The Flood'),
         ref=('Быт. 7:12', 'Gen. 7:12'),
         quote=('И лился на землю дождь сорок дней и сорок ночей.',
                'And the rain was upon the earth forty days and forty nights.'),
         s=('Дождь лил сорок дней и сорок ночей, и воды покрыли землю.',
            'The rain fell forty days and forty nights, and the waters covered the earth.'),
         a=('Вмёрзший Ковчег — след той воды. Под дождём у его обломка память возвращается.',
            'The frozen Ark is a trace of that water. In the rain beside its wreck memory returns.'),
         gloss=[]),
    dict(id='ark', book=3, node='flood', art='ark', src='tablet',
         how=('Скрижаль Сима в Ковчеге во льдах', 'The tablet of Shem in the Ark amid the ice'),
         title=('Ковчег', 'The Ark'),
         ref=('Быт. 6:15', 'Gen. 6:15'),
         quote=('Длина ковчега триста локтей; ширина его пятьдесят локтей, а высота его тридцать локтей.',
                'The length of the ark shall be three hundred cubits, the breadth of it fifty cubits, and the height of it thirty cubits.'),
         s=('Ковчег строили по мерам: триста локтей в длину, пятьдесят в ширину, тридцать в высоту.',
            'The Ark was built to measure: three hundred cubits long, fifty broad, thirty high.'),
         a=('В Чертогах стоит огромная руина: во льду пары зверей, на стене журнал Сима.',
            'A vast ruin stands in the Halls: pairs of beasts in the ice, and Shem\'s log upon the wall.'),
         gloss=['ark']),
    dict(id='dove', book=3, node='flood', art='dove', src='deed',
         how=('Масличная ветвь: призови голубя-проводника', 'The olive branch: summon the guiding dove'),
         title=('Голубь', 'The Dove'),
         ref=('Быт. 8:11', 'Gen. 8:11'),
         quote=('Голубь возвратился к нему в вечернее время, и вот, свежий масличный лист во рту у него; и узнал Ной, что вода сошла с земли.',
                'And the dove came in to him in the evening; and, lo, in her mouth was an olive leaf pluckt off: so Noah knew that the waters were abated from off the earth.'),
         s=('Голубь вернулся с масличным листом: вода сошла.', 'The dove returned with an olive leaf: the waters were gone.'),
         a=('Голубь-проводник выведет к ближайшей постройке тех, у кого есть масличная ветвь.',
            'The guiding dove leads whoever bears an olive branch to the nearest ruin.'),
         gloss=[]),
    dict(id='rainbow', book=3, node='flood', art='rainbow', src='glimpse',
         how=('Отблеск: Радужные отмели в Раю', 'A Glimpse: the Rainbow Shoals in Heaven'),
         title=('Радуга завета', 'The Rainbow of the Covenant'),
         ref=('Быт. 9:13', 'Gen. 9:13'),
         quote=None,
         s=('Радуга в облаке стала знамением завета между Богом и землёй.',
            'The rainbow in the cloud became the token of a covenant between God and the earth.'),
         a=('Радуга в Раю — не только знак, но и дорога, которую можно пройти.',
            'The rainbow in Heaven is more than a sign: it is a road that can be walked.'),
         gloss=['covenant']),
    dict(id='archons', book=3, node='flood', art='archon', src='deed',
         how=('Победи Морозного Архонта', 'Defeat the Frost Archon'),
         title=('Правители сфер', 'Rulers of the Spheres'),
         ref=('Еф. 6:12', 'Eph. 6:12'),
         quote=None,
         t=('Предание гностиков: Архонты — правители небесных сфер и тюремщики душ.',
            'Gnostic tradition: Archons are rulers of the heavenly spheres and gaolers of souls.'),
         a=('Морозный Архонт держал Инию во льду, но он был лишь тюремщиком: приказы приходили из темноты.',
            'The Frost Archon kept Inia in the ice, yet he was only a gaoler: his orders came out of the dark.'),
         gloss=['archon']),
]

# Глоссарий (LORE §5a): кто это — и что это значит здесь. id → (ru слово, en слово, ru кто, en who, ru здесь, en here)
GLOSSARY = {
    'grace': ('Благодать', 'Grace', 'Искра Света в тех, кто идёт путём ангелов.', 'A spark of Light in those who walk the way of angels.',
              'Очки Благодати открывают навыки в Кодексе.', 'Grace points unlock skills in the Codex.'),
    'seraph': ('Серафим', 'Seraph', 'Шестикрылый ангел огня, воспевающий «Свят, Свят, Свят» (Ис. 6:2–3).',
               'A six-winged angel of fire who sings "Holy, Holy, Holy" (Isa. 6:2–3).',
               'Падший Серафим стережёт Цитадель Рая.', 'The Fallen Seraph guards the Citadel of Heaven.'),
    'cherub': ('Херувим', 'Cherub', 'Ангел-страж, поставленный у Восточных врат Эдема (Быт. 3:24).',
               'A guardian angel set at the East Gate of Eden (Gen. 3:24).', 'Малые херувимы летают над Раем; великий — у врат Сада.',
               'Little cherubs fly over Heaven; the great one stands at the Garden gate.'),
    'eden': ('Эдем', 'Eden', 'Первый сад, где жили Адам и Ева.', 'The first garden, where Adam and Eve lived.',
             'Рай мода — Эдем, поднятый над облаками.', 'Heaven in this mod is Eden lifted above the clouds.'),
    'fading': ('Угасание', 'The Fading', 'Уход света из мира после изгнания.', 'The going-out of the world\'s light after the exile.',
               'Из-за него ночи длиннее, а чудовища сильнее.', 'Because of it nights grow longer and monsters stronger.'),
    'watcher': ('Страж (Григори)', 'Watcher (Grigori)', 'Ангел-наблюдатель, сошедший к людям (Книга Еноха).',
                'An angel-observer who came down to men (Book of Enoch).', 'Падшие стражи Рая и Бездны.', 'The Fallen Guardians of Heaven and the Abyss.'),
    'nephilim': ('Нефилим', 'Nephilim', 'Великан, рождённый от Стража и дочери человеческой (Быт. 6:4).',
                 'A giant born of a Watcher and a daughter of men (Gen. 6:4).', 'Мини-босс Темницы Стражей.', 'The mini-boss of the Prison of the Watchers.'),
    'metatron': ('Метатрон', 'Metatron', 'Писец небесных книг; по преданию — вознесённый Енох.',
                 'Scribe of the heavenly books; by tradition, Enoch raised up.', 'Хранитель Летописи в Цитадели.', 'Keeper of the Chronicle in the Citadel.'),
    'abyss': ('Бездна', 'The Abyss', 'Тьма под твердью, куда падают отпавшие.', 'The dark beneath the firmament, where the fallen descend.',
              'Нижнее измерение мода.', 'The lower dimension of the mod.'),
    'abaddon': ('Аваддон', 'Abaddon', '«Губитель», ангел бездны (Откр. 9:11).', '"Destroyer", the angel of the pit (Rev. 9:11).',
                'Его тень — Пожиратель Света.', 'His shadow is the Light Devourer.'),
    'archon': ('Архонт', 'Archon', '«Правитель» небесной сферы в гностических преданиях.', 'A "ruler" of a heavenly sphere in Gnostic tradition.',
               'Морозный Архонт — тюремщик Ледяных Чертогов.', 'The Frost Archon is the gaoler of the Frozen Halls.'),
    'firmament': ('Твердь', 'The Firmament', 'Небесный свод, разделивший нижние воды и верхние (Быт. 1:7).',
                  'The vault of heaven that parted the lower waters from the upper (Gen. 1:7).', 'Над ней — воды, замёрзшие в Чертогах.',
                  'Above it lie the waters that froze in the Halls.'),
    'ark': ('Ковчег', 'The Ark', 'Корабль Ноя, на котором спаслись пары живых тварей (Быт. 6–8).',
            'Noah\'s vessel on which pairs of living creatures were saved (Gen. 6–8).', 'Руина во льдах Чертогов.', 'A ruin in the ice of the Halls.'),
    'covenant': ('Завет', 'Covenant', 'Обет Бога людям; его знак — радуга (Быт. 9:13).', 'God\'s pledge to men; its sign is the rainbow (Gen. 9:13).',
                 'Радужные мосты Рая.', 'The rainbow bridges of Heaven.'),
}
